# Generated by Django 4.2.7 on 2023-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ПУСТО', max_length=50, verbose_name='Название')),
                ('description', models.CharField(default='ПУСТО', max_length=250, verbose_name='Краткое описание (кликбейт)')),
                ('image', models.CharField(default='ПУСТО', max_length=250, verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Полное описание')),
                ('date', models.DateField(verbose_name='Дата события')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
